# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-12-18 19:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('username', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('firstname', models.CharField(max_length=255)),
                ('lastname', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('strava_code', models.CharField(max_length=255)),
            ],
        ),
        migrations.DeleteModel(
            name='Greeting',
        ),
    ]
